language: r
r: 3.5.0
sudo: false
cache: packages
before_install:
  - mysql -e 'create database dbx_test;'
  - psql -c 'create database dbx_test;' -U postgres
notifications:
  email:
    on_success: never
    on_failure: change
