language: r
r: 3.6.0
sudo: false
cache: packages
addons:
  postgresql: "9.6"
before_install:
  - mysql -e 'create database dbx_test;'
  - psql -c 'create database dbx_test;' -U postgres
notifications:
  email:
    on_success: never
    on_failure: change
